title: "Lingua Latina Legenda: an open-source introduction to Latin"
subtitle: "Work in progress for use in fall '22 courses"
author: [Daniel Libatique, Dominic Machado, Neel Smith]
book: true
titlepage: true