remote_theme: pmarsceill/just-the-docs

footer_content: "All material available under the Creative Commons Attribution Share-Alike license <a href=\"https://creativecommons.org/licenses/by-sa/4.0/\">CC BY-SA 4.0 <img height=\"15\" width=\"80\" src=\"https://mirrors.creativecommons.org/presskit/buttons/80x15/png/by-sa.png\" /></a> "


aux_links:
  "PDF":
    - "https://github.com/LinguaLatina/textbook/raw/master/pdf/l3.pdf"
  "L3 home":
    - "https://lingualatina.github.io/"
  "Textbook source on github":
    - "https://github.com/lingualatina/textbook/"